
#Configurations related to materials.
[materials]
	#Should the mod find ingot materials with ores.
	ingot = true
	#Should the mod find gem materials with ores.
	gem = true
	#Should the mod find crystal materials with ores.
	crystal = true
	#Should the mod find dust materials with ores.
	dust = true
	#Should the mod find ingot materials without ores.
	ingotPlain = true
	#Should the mod find gem materials without ores.
	gemPlain = true
	#Should the mod find crystal materials without ores.
	crystalPlain = true
	#Should the mod find dust materials without ores.
	dustPlain = true

#Configurations related to material overrides.
[materialOverrides]
	#List of materials that should be gems.
	gem = ["diamond", "emerald", "lapis", "prismarine", "quartz", "niter", "sulfur", "cinnabar", "apatite"]
	#List of materials that should be crystals.
	crystal = []
	#List of materials that should be dusts.
	dust = ["glowstone", "redstone", "cassiterite", "chalcocite", "magnetite", "galena", "sheldonite"]

#Configurations related to item selection.
[itemSelection]
	#List of mods that are preferred when selecting items in recipes.
	preferredMods = ["minecraft"]

#Configurations related to block tags.
[blockTags]
	#List of block tags that should not be added.
	blacklist = []
	#List of block tags that should be considered as defined.
	customDefined = []

#Configurations related to item tags.
[itemTags]
	#List of item tags that should not be added.
	blacklist = []
	#List of item tags that should be considered as defined.
	customDefined = ["forge:ingots/cosmilite", "forge:ingots/otherworldy", "forge:ingots/infernium", "forge:ingots/ferozium", "forge:ingots/astratite", "forge:ingots/magnesium", "forge:storage_blocks/cosmilite", "forge:storage_blocks/otherworldy", "forge:storage_blocks/infernium", "forge:storage_blocks/ferozium", "forge:storage_blocks/astratite", "forge:storage_blocks/magnesium", "forge:dusts/magnetite", "forge:ores/magnetite", "forge:dusts/chalcocite", "forge:ores/chalcocite", "forge:dusts/cassiterite", "forge:ores/cassiterite", "forge:dusts/galena", "forge:ores/galena", "forge:dusts/sheldonite", "forge:ores/sheldonite"]

#Configurations related to fluid tags.
[fluidTags]
	#List of fluid tags that should not be added.
	blacklist = []
	#List of fluid tags that should be considered as defined.
	customDefined = []

#Configurations related to entity type tags.
[entityTypeTags]
	#List of entity type tags that should not be added.
	blacklist = []
	#List of entity type tags that should be considered as defined.
	customDefined = []

#Configurations related to recipes.
[recipes]
	#List of recipes that should not be added.
	blacklist = []

#Configurations related to loot tables.
[lootTables]
	#List of loot tables that should not be added.
	blacklist = []

#Configurations related to advancements.
[advancements]
	#List of advancements that should not be added.
	blacklist = []

#Configurations related to color generation.
[colors]
	#The gamma value used to blend colors.
	gammaValue = 2.0
	#Should colors of all materials be reset on next startup.
	resetColors = false

#Configurations related to material localization.
[materialLocalization]
	#Should the mod check for material localization updates.
	checkL10nUpdates = true
	#The update interval of localization files in days.
	updateInterval = 3.0

