
[general]
	#The material blacklist of this module.
	materialBlacklist = ["diamond", "copper", "redstone", "copper", "gold", "iron", "lead", "silver", "tin", "nickel", "uranium", "zinc", "aluminum"]

